### ISSUE TITLE
RcppArmadillo does it still need to be pinned?

### ISSUE THREAD

**Issue by roryk** [hms-dbmi/scde#12]
The vignette seems to run okay for me with the latest version of RcppArmadillo-- having a specific old version as a default makes it tough to include as a dependency. Do you think maybe the version could get unpinned?

**Comment by JEFworks** [comment]
Hi Rory,

RcppArmadillo v0.5 underwent some major changes such that it is no longer compatible with our package. Any version pre v0.5 should work, though I've only tested 0.4.650.1.1. I'm also not sure if syntactically a description dependency like RcppArmadillo (< 0.5, > 0.4) would work so I've kept 0.4.650.1.1 as the specific old version as the default.

I have [opened up an issue with RcppArmadillo already](https://github.com/RcppCore/RcppArmadillo/issues/49) and have been in touch with Dirk and Conrad, so hopefully it will be resolved soon.  Once it is resolved, I will update to require (>= 0.X).

Best,
Jean

**Comment by roryk** [comment]
Thanks Jean for following up. Let me know if I can be of any help.

**Comment by JEFworks** [comment]
Hi Rory,

RcppArmadillo v0.5.400.2.0 recently came out and has fixed the pre-v0.5 compatibility issues. I've since updated the DESCRIPTION file to require RcppArmadillo >= 0.5.400.2.0. Hopefully this will make the package a bit easier to install and use. Travis testing has passed but let me know if you get a chance to try it out and if anything breaks!

Best,
Jean

**Comment by roryk** [comment]
Thanks Jean for spending the time on this and following up, seems like it is working great.
